### ISSUE TITLE
Tooltip doesn't disappear

### ISSUE THREAD

**Issue by slegrand45** [debois/elm-mdl#240] opened 2016-10-03 15:20 UTC
Hello,

The following demo gives an example of the problem: https://slegrand45.github.io/test.site/www/

When you click on the "add" icon, the tooltip is correctly displayed and the page content changes. Then, when you click on the "list" icon, the previous content is displayed again but also the tooltip. Despite the fact that the mouse is not on the "add" icon.

Is there a workaround to avoid this behavior? I tested with Firefox 48 and Chrome 52.0.2743.116, both on Linux. The source code of the demo is available here: https://github.com/slegrand45/test.site/blob/master/Main.elm

Thanks.

**Comment by vipentti** [comment] 2016-10-03 15:57
Thanks for reporting this! Can verify this on Windows 10 and Chrome  54.0.2840.41 beta-m (64-bit). I'll take a closer look and see if I can find the cause, I believe it might be something to do with Tooltip currently using 'mouseleave' which might not be triggered properly when the click event causes the update to be called.

**Comment by rofrol** [comment] 2016-12-28 23:22
Bug can be close. Tested with elm-mdl-8.0.0.

Example code https://github.com/rofrol/elm-mdl-bug-240

**Comment by slegrand45** [comment] 2017-01-06 14:58
By the way, it's also visible on the [Tooltips demo page](https://debois.github.io/elm-mdl/#tooltips) but only with the button example (the "Click Me!" button).

**Comment by kittykatattack** [comment] 2017-01-06 16:47
Hi everyone, I just want to confirm that I'm experiencing the same problem.

**Comment by debois** [comment] 2017-01-10 13:48
Can someone check out if this is a known bug from upstream?

**Comment by vipentti** [comment] 2017-02-24 07:07
This is a bug due to how the events are handled currently

**Comment by aforemny** [comment] 2017-07-11 09:17
There are two issues being discussed here. The original issue relates to the fact that the tooltip does not disappear when you remove an element from DOM: apparently it does not fire the mouseleave event which is required for the Tooltip to hide correctly. I do not know any way around this.

The other issue that mentions the Tooltips demo page should be resolved in current new-v8. You can verify if it has been resolved in the [wip demo](https://debois.github.io/elm-mdl/wip.html#tooltips).

**Closed** 2017-07-11 09:17 UTC
Labels: bug, in progress
