### ISSUE TITLE
Menu Bug Background

### ISSUE THREAD

**Issue by OvermindDL1** [debois/elm-mdl#121] opened 2016-07-27 20:13 UTC
Same bug happens on the demo site at https://debois.github.io/elm-mdl/#menus as well as demonstrated with backgrounds to differentiate easily at:  https://overminddl1.com/screenshots/work/MDL-Menu-Bug1.png
![Bug demonstration](https://overminddl1.com/screenshots/work/MDL-Menu-Bug1.png)
In the above picture shows a Menu (in the wrong place, but see bug #118 about that), with two items.

If you notice, the menu item that the mouse is over shows two background colors, the lighter is of the entire selected line, the second is of the icon and text within it.  If I click on the darker one it will call my event that I registered on my (modified) onClick.  If I click on the lighter one then it sends a message on its click, via Mdl, but only thing it does close the menu, it does not call my callback.  As seen at https://github.com/debois/elm-mdl/blob/master/src/Material/Menu.elm#L447 there is a lift for it, however the lift has two issues, the first of which being that the message cannot be set per row, it is 'global for the menu', and second that the onClick does not support changing the default options, such as stop_propagation and such.

**Comment by OvermindDL1** [comment] 2016-07-27 21:37
For note, I would actually prefer if menu did not have its own message for those at all, I would prefer if my menu items handled it themselves, but I am not seeing a way to disable the menu event without entirely disabling the menu entry.

**Comment by debois** [comment] 2016-07-28 10:42
I think this is a duplicate of #112 and #119(2). Let me know if I'm mistaken and I'll re-open.

**Comment by OvermindDL1** [comment] 2016-07-28 15:22
#112 is a duplicate of part of the issue, the other issue is that the onClick handler on the #112 part is not per-element, I need each element to have their own message handler, in this case I think the onClick on the menu Items should be removed.  If someone wants it to be clickable and send a message then they should do that in their own Item's HTML.  So perhaps this should be re-opened to remove the default onClick handler on the Menu Items as it seems superfluous (it is not even used in the Demo, Item-specific handlers are).

**Comment by debois** [comment] 2016-07-28 17:43
Ok, I see.

**Comment by OvermindDL1** [comment] 2016-07-28 17:50
Actually the onClick handler on a menu could be left, but remove it from the Items and instead put it on the menu open/close.  Being able to react to when the menu is opening and closing would be very useful for a menu I just made here.

**Comment by debois** [comment] 2016-08-01 07:24
Non-duplicate part moved to #129.

**Closed by debois** 2016-08-01 07:24 UTC
Labels: duplicate

**Comment by OvermindDL1** [comment] 2016-08-03 23:10
Live demo appears to have this fixed, will test my own code when I update tomorrow.  :-)

**Comment by debois** [comment] 2016-08-04 04:37
Excellent :)
