### ISSUE TITLE
Layout link does not react to Enter or Space keys

### ISSUE THREAD

**Issue by gotcha** [debois/elm-mdl#254] opened 2016-11-17 11:35 UTC
Steps to reproduce:

1. Navigate to https://debois.github.io/elm-mdl/
2. Press Tab until `github` link in the header gets focus
3. Press Enter or Space; nothing happens

It should actually follow the link / send the `onClick` message.

I'd be happy to contribute a PR but would need some hints how to tackle this issue.

**Comment by gotcha** [comment] 2016-11-17 11:49
Oops, just occured to me, this could be due to the Vimium extension.

So I tried in Firefox, the procedure above does actually work on Elm-mdl demo.
Same for Chrome without Vimium.

The link in the Elm-mdl demo header does not use `onClick`.

However, `Material.Layout.link` setup with `Material.layout.onClick` does not get triggered by Enter or Space keys. This happens both in Firefox and Chrome.

**Comment by debois** [comment] 2016-12-28 13:52
@gotcha: Could you supply an exact means of reproducing, like in your first post? I'm not entirely sure what it is that is broken ;)

**Comment by hakonrossebo** [comment] 2017-01-09 19:01
I checked this now. I'm also using the Vimium plugin with Chrome. When tabbing to the Github link and pressing enter, it navigates to the link. Pressing space does not seem to navigate. This seems to be the same effect when verified against the mdl upstream. Suggest we can close this issue

**Comment by debois** [comment] 2017-01-10 14:08
So this is a Vimium issue that's also present in upstream; and without Vimium we can't reproduce? In that case, please close ;)

**Comment by hakonrossebo** [comment] 2017-01-12 12:16
Sorry, was not clear. What I meant was that I use Vimium and that everything seems to work as expected. Closing the issue.

**Closed by hakonrossebo** 2017-01-12 12:16 UTC
Labels: bug
