### ISSUE TITLE
Last Tab cut off when working in tablet/mobile screens

### ISSUE THREAD

**Issue by uptoit** [debois/elm-mdl#295] opened 2017-03-12 07:06 UTC
The last tab in the layout is cut off when the screen size is smaller than desktop. Seems the chevron's length is not calculated correctly in non-desktop screens.

**Comment by aforemny** [comment] 2017-06-30 13:19
I cannot reproduce it in the (current v8 demo)[https://debois.github.io/elm-mdl/], so I am closing. If you still experience this issue, please re-open and maybe send a screenshot?

**Closed as completed by aforemny** 2017-06-30 13:19 UTC
